FORMAT: 1A

# Veo Core API
The Veo Core API powers the website and device integrations within the Veo architecture

Please be sure to validate your response examples with [JSONLint][1].

[1]:  http://jsonlint.com/

# Group Asset
Represents actions against Asset objects

## Asset [/asset/{id}]
Represents an Asset

+ Parameters
    + id (string, `1`) ... The id of the Asset.

+ Model (application/json)

    ```js
    {
        "data": {
            "type": "Asset",
            "assetType": "Movie",
            "id": 4754,
            "status": "published",
            "createdAt": "2013-08-23 19:07:49",
            "modifiedAt": "2014-08-07 02:50:31",
            "title": "Operación Dragón",
            "synopsisShort": "Un maestro de artes marciales decide espiar a un solitario criminal usando su invitación a un torneo.",
            "synopsisLong": "Un maestro de artes marciales decide espiar a un solitario criminal usando su invitación a un torneo. Es la película que tras estrenarse en Hong Kong, dio a conocer a Bruce Lee en Estados Unidos.",
            "keywords": "dragon",
            "duration": "01:42",
            "startYear": 1973,
            "endYear": 1980,
            "externalBillingId": "000557397",
            "parentalRating": {
                "id": 9,
                "title": "R"
            },
            "mainGenre": {
                "id": 111,
                "title": "Acción y Aventura"
            },
            "genres": [
                {
                    "id": 111,
                    "title": "Acción y Aventura"
                },
                {
                    "id": 112,
                    "title": "Dibujos Animados"
                }
            ],
            "distributor": {
                "id": 12,
                "name": "Warner Bros."
            },
            "studio": {
                "id": 22,
                "name": "WDD"
            },
            "people": [
                {
                    "id": 7312,
                    "role": "Actor",
                    "communicationName": "John Saxon"
                },
                {
                    "id": 7313,
                    "role": "Actor",
                    "communicationName": "Bruce Lee"
                },
                {
                    "id": 7314,
                    "role": "Director",
                    "communicationName": "Robert Clouse"
                },
                {
                    "id": 15010,
                    "role": "Actor",
                    "communicationName": "Jim Kelly"
                },
                {
                    "id": 15011,
                    "role": "Actor",
                    "communicationName": "Ahna Capri"
                }
            ],
            "pictures": [
                {
                    "type": "Picture",
                    "id": 2853,
                    "status": "published",
                    "modifiedAt": "2014-03-28 00:25:46",
                    "credits": "Tom Smith",
                    "orientation": "portrait",
                    "pictureType": "Poster",
                    "title": "",
                    "versions": [
                        {
                            "profile": "webLandscapeSmall",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile150Image.jpg",
                            "width": "192",
                            "height": "108"
                        },
                        {
                            "profile": "webLandscapeMedium",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "224",
                            "height": "126"
                        },
                        {
                            "profile": "webLandscapeLarge",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "384",
                            "height": "216"
                        },
                        {
                            "profile": "mobileLandscapeSmall",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "96",
                            "height": "54"
                        },
                        {
                            "profile": "mobileLandscapeMedium",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "160",
                            "height": "90"
                        },
                        {
                            "profile": "mobileLandscapeLarge",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "320",
                            "height": "180"
                        },
                        {
                            "profile": "mobileRetinaLandscapeSmall",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "192",
                            "height": "108"
                        },
                        {
                            "profile": "mobileRetinaLandscapeMedium",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "320",
                            "height": "180"
                        },
                        {
                            "profile": "mobileRetinaLandscapeLarge",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "640",
                            "height": "360"
                        }
                    ]
                }
            ],
            "videos": [
                {
                    "type": "Video",
                    "id": 4533,
                    "status": "published",
                    "audioLanguage": {
                        "id": 3,
                        "title": "English"
                    },
                    "audioType": "Stereo",
                    "definition": "SD",
                    "duration": "01:42:29",
                    "files": [
                        {
                           "path": "http://vodhds-video.cablevision.veo.tv/veo_4533/veo_4533__CV_MP4_SD_16x9_1600kbps_640x480_29.97fps.f4m",
                           "type": "HDS" 
                        },
                        {
                           "path": "http://vodhls-video.cablevision.veo.tv/veo_4533__CV/veo_4533__CV.m3u8",
                           "type": "HLS" 
                        },
                        {
                           "path": "http://vodss-video.cablevision.veo.tv/veo_4533__CV/veo_4533__CV.ism/Manifest",
                           "type": "SS" 
                        }
                    ],
                    "resolution": "480i",
                    "screenFormat": "Widescreen",
                    "videoType": "full"
                }
            ],
            "publicationEvent": {
                "type": "PublicationEvent",
                "id": 18563,
                "status": "published",
                "createdAt": "2013-08-23 19:07:49",
                "modifiedAt": "2014-08-07 02:50:31",
                "startDate": "2014-04-09 06:00:00",
                "endDate": "2015-03-31 05:59:00",
                "billingType": "rental",
                "price": "25.00",
                "userId": 3
            }
        },
        "messages": []
    }
    ```

### Retrieve a Asset [GET]
Returns a specific Asset.

+ Response 200

    [Asset][]


## List Assets [/assets]
Returns all Assets.

+ Model (application/json)

    ```js
    {
        "data": [
        {
            "type": "Asset",
            "assetType": "Movie",
            "id": 4754,
            "status": "published",
            "title": "Operación Dragón",
            "synopsisShort": "Un maestro de artes marciales decide espiar a un solitario criminal usando su invitación a un torneo.",
            "duration": "01:42",
            "parentalRating": {
                "id": 9,
                "title": "R"
            },
            "mainGenre": {
                "id": 111,
                "title": "Acción y Aventura"
            },
            "pictures": [
                {
                    "type": "Picture",
                    "id": 2853,
                    "status": "published",
                    "modifiedAt": "2014-03-28 00:25:46",
                    "credits": "Tom Smith",
                    "orientation": "portrait",
                    "pictureType": "Poster",
                    "title": "",
                    "versions": [
                        {
                            "profile": "webLandscapeSmall",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile150Image.jpg",
                            "width": "192",
                            "height": "108"
                        },
                        {
                            "profile": "webLandscapeMedium",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "224",
                            "height": "126"
                        },
                        {
                            "profile": "webLandscapeLarge",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "384",
                            "height": "216"
                        },
                        {
                            "profile": "mobileLandscapeSmall",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "96",
                            "height": "54"
                        },
                        {
                            "profile": "mobileLandscapeMedium",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "160",
                            "height": "90"
                        },
                        {
                            "profile": "mobileLandscapeLarge",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "320",
                            "height": "180"
                        },
                        {
                            "profile": "mobileRetinaLandscapeSmall",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "192",
                            "height": "108"
                        },
                        {
                            "profile": "mobileRetinaLandscapeMedium",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "320",
                            "height": "180"
                        },
                        {
                            "profile": "mobileRetinaLandscapeLarge",
                            "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                            "width": "640",
                            "height": "360"
                        }
                    ]
                }
            ],
            "publicationEvent": {
                "type": "PublicationEvent",
                "id": 18563,
                "status": "published",
                "startDate": "2014-04-09 06:00:00",
                "endDate": "2015-03-31 05:59:00",
                "billingType": "rental",
                "price": "25.00"
            }
        }
        ],
        "messages": []
    }
    ```

### Retrieve all Assets [GET]
Retrieves all assets.

+ Response 200

    [List Assets][]


# Group Country
Represents actions against Country object

## List Countries [/countries]
A List of all countries.

+ Model (application/json)

    ```js
        {
            "data": [
                {
                    "id": 1,
                    "parentId": 0,
                    "title": "United States",
                    "type": "Country"
                },
                {
                    "id": 2,
                    "parentId": 0,
                    "title": "México",
                    "type": "Country"
                }
            ],
            "messages": [
                {
                    "success": "Data successfully retrieved"
                }
            ]
        }
    ```

### Retrieve all Countries [GET]
Retrieves all Countries.

+ Response 200

    [List Countries][]

# Group Genre
Represents actions against Genre object

## Genre [/genre/{id}]
Represents a genre

+ Parameters
    + id (string, `1`) ... The id of the Genre.

+ Model (application/json)

    ```js
        {
            "data": {
                "id": 3,
                "parentId": 0,
                "title": "Action",
                "type": "Genre"
            },
            "messages": [
                {
                    "success": "Data successfully retrieved"
                }
            ]
        }
    ```

### Retrieve a Genres [GET]
Returns a specific Genres.

+ Response 200

    [Genre][]

## List Genres [/genres]
Retrieve a List of all published Genres.

+ Model (application/json)

    ```js
        {
            "data": [
                {
                    "id": 3,
                    "parentId": 0,
                    "title": "Action",
                    "type": "Genre"
                },
                {
                    "id": 4,
                    "parentId": 0,
                    "title": "Spanish",
                    "type": "Genre"
                }
            ],
            "messages": [
                {
                    "success": "Data successfully retrieved"
                }
            ]
        }
    ```

### Retrieve all Genres [GET]
Retrieves all Genres.

+ Response 200

    [List Genres][]

# Group Geoblocking
Represents actions against Geoblocking object

## List Geoblocking [/geoblockings]
Retrieve a List of all published Geoblocking.

+ Model (application/json)

    ```js
        {
            "data": [
                {
                    "id": 1,
                    "title": "Guatemala",
                    "type": "Geoblocking"
                },
                {
                    "id": 2,
                    "title": "Italy",
                    "type": "Geoblocking"
                }
            ],
            "messages": [
                {
                    "success": "Data successfully retrieved"
                }
            ]
        }
    ```

### Retrieve all Geoblocking [GET]
Retrieves all Geoblocking.

+ Response 200

    [List Geoblocking][]

# Group Navigation
Represents actions against SB Navigation objects

## Navigation [/navigation]
Returns all menus for clients (WEB, IOS, Android, ...).

+ Model (application/json)

    ```js
    {
        "data": [
            {
                "id": 1,
                "type": "Navigation",
                "title": "Main menu",
                "key": "main-menu",
                "items": [
                    {
                        "id": 10,
                        "type": "Navigation",
                        "title": "Tele para llevar",
                        "key": "main-menu-tele-para-llevar",
                        "link": "/tv/epg",
                        "icon": null
                    },
                    {
                        "id": 11,
                        "type": "Navigation",
                        "title": "Play",
                        "key": "main-menu-play",
                        "link": "/clubondemand",
                        "icon": null
                    },
                    {
                        "id": 12,
                        "type": "Navigation",
                        "title": "Rentas",
                        "key": "main-menu-rentas",
                        "link": "/tienda",
                        "icon": null
                    }
                ]
            },
            {
                "id": 2,
                "type": "Navigation",
                "title": "Clubondemand",
                "key": "clubondemand",
                "items": [
                    {
                        "id": 20,
                        "type": "Navigation",
                        "title": "Inicio",
                        "key": "clubondemand-inicio",
                        "link": "/clubondemand",
                        "icon": null
                    },
                    {
                        "id": 21,
                        "type": "Navigation",
                        "title": "Películas",
                        "key": "clubondemand-peliculas",
                        "link": "/clubondemand/peliculas",
                        "icon": null
                    },
                    {
                        "id": 22,
                        "type": "Navigation",
                        "title": "Series de TV",
                        "key": "clubondemand-series-de-tv",
                        "link": "/clubondemand/series",
                        "icon": null
                    },
                    {
                        "id": 23,
                        "type": "Navigation",
                        "title": "Telenovelas",
                        "key": "clubondemand-telenovelas",
                        "link": "/clubondemand/telenovelas",
                        "icon": null
                    }
                ]
            },
            {
                "id": 3,
                "type": "Navigation",
                "title": "Tienda",
                "key": "tienda",
                "items": [
                    {
                        "id": 24,
                        "type": "Navigation",
                        "title": "Inicio",
                        "key": "tienda-inicio",
                        "link": "/tienda",
                        "icon": null
                    },
                    {
                        "id": 25,
                        "type": "Navigation",
                        "title": "Catálogo Completo",
                        "key": "tienda-catalogo-completo",
                        "link": "/tienda/peliculas",
                        "icon": null
                    }
                ]
            }
        ]
    }
    ```

### Retrieve all menus [GET]
Retrieves all navigation menus for clients.

+ Response 200

    [Navigation][]

## Navigation item [/navigation/{key}]
Returns a navigation item.

+ Parameters
    + key (string, `main-menu`) ... The key of the navigation.

+ Model (application/json)

    ```js
    {
        "data": {
            "id": 1,
            "type": "Navigation",
            "title": "Main menu",
            "key": "main-menu",
            "items": [
                {
                    "id": 10,
                    "type": "Navigation",
                    "title": "Tele para llevar",
                    "key": "main-menu-tele-para-llevar",
                    "link": "/tv/epg",
                    "icon": null
                },
                {
                    "id": 11,
                    "type": "Navigation",
                    "title": "Play",
                    "key": "main-menu-play",
                    "link": "/clubondemand",
                    "icon": null
                },
                {
                    "id": 12,
                    "type": "Navigation",
                    "title": "Rentas",
                    "key": "main-menu-rentas",
                    "link": "/tienda",
                    "icon": null
                }
            ]
        }
    }
    ```

### Retrieve menu [GET]
Retrieves one navigation menu by key.

+ Response 200

    [Navigation item][]

# Group Parental Rating
Represents actions against Parental Rating object

## List Parental Rating [/parental-ratings]
Retrieve a List of all published ParentalRating.

+ Model (application/json)

    ```js
        {
            "data": [
                {
                    "id": 1,
                    "title": "G",
                    "code": "G",
                    "level": 0,
                    "type": "ParentalRating"
                },
                {
                  "id": 2,
                  "title": "PG",
                  "code": "PG",
                  "level": 1,
                  "type": "ParentalRating"
                }
            ],
            "messages": [
                {
                    "success": "Data successfully retrieved"
                }
            ]
        }
    ```

### Retrieve all Parental Rating [GET]
Retrieves all Parental Rating.

+ Response 200

    [List Parental Rating][]

# Group PlayContext
Actions required for playing and tracking video streaming

## Initialize asset streaming [/play/asset/{assetId}/video/{videoId}]
Create the Asset PlayContext required before streaming.

+ Parameters
    + assetId (string, `4962`) ... The id of the Asset.
    + videoId (string, `6538`) ... The id of the VideoAsset.

+ Model (application/json)

    ```js
    {
        "data": {
            "playContext": {
                "locationUri": "http://www.veo.tv/player/user/1811/asset/4962/video/6538/stream/b7648850-1f21-4031-9cb3-e3a19eb800fb",
                "playerState": null,
                "userStream": {
                    "videoId": 6538,
                    "assetId": 4962,
                    "userId": 1181,
                    "streamId": "b7648850-1f21-4031-9cb3-e3a19eb800fb",
                    "expirationDate": null,
                    "interval": -1,
                    "updateDate": 1418330651212,
                    "creationDate": 1418330651212,
                    "state": "CREATED"
                }
            }
        }
    }
    ```

### Create Asset PlayContext [POST]

+ Response 200

    [Initialize asset streaming][]

## Initialize channel streaming [/watch/channel/{channelName}]
Create the Channel PlayContext required before streaming.

+ Parameters
    + channelName (string, `GALA TV HD`) ... The name of the Channel.

+ Model (application/json)

    ```js
    {
        "data": {
            "playContext": {
                "locationUri": "http://www.veo.tv:80/player/user/991580/channel/909/stream/a902f568-04b5-46a6-ae53-9cebde7b54a6",
                "playerState": null,
                "userStream": {
                    "channelNumber": 909,
                    "userId": 991580,
                    "streamId": "a902f568-04b5-46a6-ae53-9cebde7b54a6",
                    "expirationDate": null,
                    "interval": -1,
                    "updateDate": 1420737389235,
                    "creationDate": 1420737389235,
                    "state": "CREATED"
                }
            }
        }
    }
    ```

### Create Channel PlayContext [POST]

+ Response 200

    [Initialize channel streaming][]

## Update Asset PlayContext [/player/user/{userId}/asset/{assetId}/video/{videoId}/stream/{streamId}]
Update the Asset PlayContext while streaming.

+ Parameters
    + userId (string, `1181`) ... The id of the User.
    + assetId (string, `4962`) ... The id of the Asset.
    + videoId (string, `6538`) ... The id of the VideoAsset.
    + streamId (string, `b7648850-1f21-4031-9cb3-e3a19eb800fb`) ... The id of the stream generated with the initial post.

+ Model (application/json)

    ```js
    {
        "data": {
            "playContext": {
                "locationUri": null,
                "playerState": "CONTINUE",
                "userStream": {
                    "videoId": 6538,
                    "assetId": 4962,
                    "userId": 1181,
                    "streamId": "b7648850-1f21-4031-9cb3-e3a19eb800fb",
                    "expirationDate": null,
                    "interval": 60,
                    "updateDate": 1418332300438,
                    "creationDate": 1418331996427,
                    "state": "RETAINED"
                }
            }
        }
    }
    ```

### Update Asset PlayContext [POST]

+ Response 200

    [Update Asset PlayContext][]

## Update Channel PlayContext [/player/user/{accountId}/channel/{channelNumber}/stream/{streamId}]
Update the Channel PlayContext while streaming.

+ Parameters
    + accountId (string, `1181`) ... The accountId of the User.
    + channelNumber (string, `909`) ... The number of the Channel.
    + streamId (string, `a902f568-04b5-46a6-ae53-9cebde7b54a6`) ... The id of the stream generated with the initial post.

+ Model (application/json)

    ```js
    {
        "data": {
            "playContext": {
                "locationUri": null,
                "playerState": "START",
                "userStream": {
                    "channelNumber": 909,
                    "userId": "501000000129-01",
                    "expirationDate": null,
                    "streamId": "a902f568-04b5-46a6-ae53-9cebde7b54a6",
                    "interval": 60,
                    "updateDate": 1420494077906,
                    "creationDate": 1420494077752,
                    "state": "ACQUIRED"
                }
            }
        }
    }
    ```

### Update Channel PlayContext [POST]

+ Response 200

    [Update Channel PlayContext][]


# Group Program
Represents actions against Program objects

## Program [/program/{id}]
Represents a Program

+ Parameters
    + id (string, `1`) ... The id of the Program.

+ Model (application/json)

    ```js
    {
        "data": {
            "type": "Program",
            "programType": "LinearEpisodeProgram",
            "id": 3,
            "status": "published",
            "modifiedAt": "2014-03-28 00:25:46",
            "duration": 2,
            "isHd": false,
            "isLive": false,
            "keywords": null,
            "areRightsBlocked": false,
            "mainGenre": {
                "id": 111,
                "title": "Acción y Aventura"
            },
            "packageCode": null,
            "parentalRating": {
                "id": 9,
                "title": "R"
            },
            "synopsisShort": "Karen cuida de Zach",
            "synopsisLong": "Karen cuida de Zach",
            "showType": "Series",
            "title": "Co-Ed Confidential 4",
            "year": 2010
        },
        "messages": []
    }
    ```

### Retrieve a Program [GET]
Returns a specific Program.

+ Response 200

    [Program][]


## List Programs [/programs]
Returns all Programs.

+ Model (application/json)

    ```js
    {
        "data": [
            {
                "type": "Program",
                "programType": "LinearEpisodeProgram",
                "id": 3,
                "modifiedAt": "2014-03-28 00:25:46",
                "duration": 2,
                "isHd": false,
                "isLive": false,
                "areRightsBlocked": false,
                "mainGenre": {
                    "id": 111,
                    "title": "Acción y Aventura"
                },
                "parentalRating": {
                    "id": 9,
                    "title": "R"
                },
                "synopsisShort": "Karen cuida de Zach",
                "showType": "Series",
                "title": "Co-Ed Confidential 4",
                "year": 2010
            }
        ],
        "messages": []
    }
    ```

### Retrieve all Programs [GET]
Retrieves all Programs.

+ Response 200

    [List Programs][]
    
# Group Search
Represents the search engine

## Search Assets [/search{?query}{?view}{?sort}{?filter}{?pageNumber}{?videoFormat%5B%5D*}]
Search result for assets search

+ Model (application/json)

    ```js
    {
        "data": {
            "total": 1,
            "summary": [
                {
                    "total": 25,
                    "showType": "Movies"
                },
                {
                    "total": 7,
                    "showType": "Telenovelas"
                },
                {
                    "total": 2,
                    "showType": "TV_Series"
                },
                {
                    "total": 0,
                    "showType": "News"
                },
                {
                    "total": 0,
                    "showType": "Shows"
                },
                {
                    "total": 0,
                    "showType": "Sports"
                },
                {
                    "total": 16,
                    "showType": "Rental"
                }
            ],
            "results": [
                {
                    "type": "Asset",
                    "assetType": "Movie",
                    "id": 4754,
                    "status": "published",
                    "title": "Operación Dragón",
                    "synopsisShort": "Un maestro de artes marciales decide espiar a un solitario criminal usando su invitación a un torneo.",
                    "duration": "01:42",
                    "startYear": 1973,
                    "parentalRating": {
                        "id": 9,
                        "title": "R"
                    },
                    "mainGenre": {
                        "id": 111,
                        "title": "Acción y Aventura"
                    },
                    "pictures": [
                        {
                            "type": "Picture",
                            "id": 2853,
                            "status": "published",
                            "modifiedAt": "2014-03-28 00:25:46",
                            "credits": "Tom Smith",
                            "orientation": "portrait",
                            "pictureType": "Poster",
                            "title": "",
                            "versions": [
                                {
                                    "profile": "webLandscapeSmall",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile150Image.jpg",
                                    "width": "192",
                                    "height": "108"
                                },
                                {
                                    "profile": "webLandscapeMedium",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "224",
                                    "height": "126"
                                },
                                {
                                    "profile": "webLandscapeLarge",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "384",
                                    "height": "216"
                                },
                                {
                                    "profile": "mobileLandscapeSmall",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "96",
                                    "height": "54"
                                },
                                {
                                    "profile": "mobileLandscapeMedium",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "160",
                                    "height": "90"
                                },
                                {
                                    "profile": "mobileLandscapeLarge",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "320",
                                    "height": "180"
                                },
                                {
                                    "profile": "mobileRetinaLandscapeSmall",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "192",
                                    "height": "108"
                                },
                                {
                                    "profile": "mobileRetinaLandscapeMedium",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "320",
                                    "height": "180"
                                },
                                {
                                    "profile": "mobileRetinaLandscapeLarge",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "640",
                                    "height": "360"
                                }
                            ]
                        }
                    ],
                    "publicationEvent": {
                        "type": "PublicationEvent",
                        "id": 18563,
                        "status": "published",
                        "startDate": "2014-04-09 06:00:00",
                        "endDate": "2015-03-31 05:59:00",
                        "billingType": "rental",
                        "price": "25.00"
                    }
                }
            ]
        },
        "messages": []
    }
    ```

### Search Assets [GET]
+ Parameters
    + query (required, string, `amor%20mio`) ... The search term
    + view = `title` (optional, string, `title`) ... Filter for Asset type and Programs
        + Values
            + `title` ... For Assets types 'Movie' and 'Series'
            + `video` ... For Assets types 'Movie' and 'Episode'
            + `tv`    ... For Programs
    + sort = `2` (optional, number, `2`) ... Results sorting
        + Values
            + `1` ... Most popular. Sorts by view_count.
            + `2` ... Most recent. Sorts by year.
            + `3` ... Best rated. Sorts by average_rating.
            + `4` ... Title. Sorts by sort_title.
            + `5` ... Sorts by relevance.
    + filter (optional, string, `movies`) ... Filter by Asset showType and billingType.
        + Values
            + `movies`      ... For 'Movies' showType.
            + `tv_series`   ... For 'TV_series' showType.
            + `telenovelas` ... For 'Telenovelas' showType.
            + `rental`      ... For 'renta' billingType.
    + pageNumber = `1` (optional, number, `2`) ... Page number for pagination.
    + videoFormat (optional, string, `SS`) ... Filter by video formats.
        + Values
            + `SS`
            + `HLS`
            + `HDS`

+ Response 200

    [Search Assets][]

# Group Browse
Returns filtered Asset

## Browse Assets [/browse/{billingType}/{showType}{?sort}{?parental}{?genre%5B%5D*}{?atoz%5B%5D*}{?decade%5B%5D*}{?collection%5B%5D*}{?pageNumber}{?videoFormat%5B%5D*}]
Results for asset browsing

+ Parameters
    + billingType (required, string, `subscription`) ... Asset's billing type.
        + Values
            + `subscription`
            + `rental`
    + showType (required, string, `movies`) ... Asset's showType.
        + Values
            + `movies`
            + `tv_series`
            + `telenovelas`
            
+ Model (application/json)

    ```js
    {
        "data": {
            "total": 1,
            "results": [
                {
                    "type": "Asset",
                    "assetType": "Movie",
                    "id": 4754,
                    "status": "published",
                    "title": "Operación Dragón",
                    "synopsisShort": "Un maestro de artes marciales decide espiar a un solitario criminal usando su invitación a un torneo.",
                    "duration": "01:42",
                    "startYear": 1973,
                    "parentalRating": {
                        "id": 9,
                        "title": "R"
                    },
                    "mainGenre": {
                        "id": 111,
                        "title": "Acción y Aventura"
                    },
                    "pictures": [
                        {
                            "type": "Picture",
                            "id": 2853,
                            "status": "published",
                            "modifiedAt": "2014-03-28 00:25:46",
                            "credits": "Tom Smith",
                            "orientation": "portrait",
                            "pictureType": "Poster",
                            "title": "",
                            "versions": [
                                {
                                    "profile": "webLandscapeSmall",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile150Image.jpg",
                                    "width": "192",
                                    "height": "108"
                                },
                                {
                                    "profile": "webLandscapeMedium",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "224",
                                    "height": "126"
                                },
                                {
                                    "profile": "webLandscapeLarge",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "384",
                                    "height": "216"
                                },
                                {
                                    "profile": "mobileLandscapeSmall",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "96",
                                    "height": "54"
                                },
                                {
                                    "profile": "mobileLandscapeMedium",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "160",
                                    "height": "90"
                                },
                                {
                                    "profile": "mobileLandscapeLarge",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "320",
                                    "height": "180"
                                },
                                {
                                    "profile": "mobileRetinaLandscapeSmall",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "192",
                                    "height": "108"
                                },
                                {
                                    "profile": "mobileRetinaLandscapeMedium",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "320",
                                    "height": "180"
                                },
                                {
                                    "profile": "mobileRetinaLandscapeLarge",
                                    "link": "https://cdnassets.veo.tv/prod/Picture/C_1_Picture_7315_profile151Image.jpg",
                                    "width": "640",
                                    "height": "360"
                                }
                            ]
                        }
                    ],
                    "publicationEvent": {
                        "type": "PublicationEvent",
                        "id": 18563,
                        "status": "published",
                        "startDate": "2014-04-09 06:00:00",
                        "endDate": "2015-03-31 05:59:00",
                        "billingType": "rental",
                        "price": "25.00"
                    }
                }
            ]
        },
        "messages": []
    }
    ```

### Browse Assets [GET]
+ Parameters
    + sort = `2` (optional, number, `2`) ... Results sorting
        + Values
            + `1` ... Most popular. Sorts by view_count.
            + `2` ... Most recent. Sorts by year.
            + `3` ... Best rated. Sorts by average_rating.
            + `4` ... Title. Sorts by sort_title.
            + `5` ... Sorts by relevance.
    + parental (optional, string, `PG-13`) ... Filter by Asset rating (Parental Rating).
        + Values
            + `A`
            + `AA`
            + `B`
            + `B15`
            + `C`
            + `D`
            + `G`
            + `NC-17`
            + `NR`
            + `PG`
            + `PG-13`
            + `R`
            + `UR`
    + genre (optional, string, `Drama`) ... Filter Asset by genre.
    + atoz (optional, number, `1`) ... Filter Asset by title first letter.
    + decade (optional, number, `1`) ... Filter Asset by year range.
    + collection (optional, number, `1`) ... Filter Asset by collection.
    + pageNumber = `1` (optional, number, `2`) ... Page number for pagination.
    + videoFormat (optional, string, `SS`) ... Filter by video formats.
        + Values
            + `SS`
            + `HLS`
            + `HDS`

+ Response 200

    [Browse Assets][]