FORMAT: 1A

# Veo Core API
The Veo Core API powers the website and device integrations within the Veo architecture

Please be sure to validate your response examples with [JSONLint][1].

[1]:  http://jsonlint.com/

# Group Country
Represents actions against Country object

## List Countries [/countries]
A List of all countries.

+ Model (application/json)

    ```js
        {
            "data": [
                {
                    "id": 1,
                    "parentId": 0,
                    "title": "United States",
                    "type": "Country"
                },
                {
                    "id": 2,
                    "parentId": 0,
                    "title": "México",
                    "type": "Country"
                }
            ],
            "messages": [
                {
                    "success": "Data successfully retrieved"
                }
            ]
        }
    ```

### Retrieve all Countries [GET]
Retrieves all Countries.

+ Response 200

    [List Countries][]

# Group Genre
Represents actions against Genre object

## Genre [/genre/{id}]
Represents a genre

+ Parameters
    + id (string, `1`) ... The id of the Genre.

+ Model (application/json)

    ```js
        {
            "data": {
                "id": 3,
                "parentId": 0,
                "title": "Action",
                "type": "Genre"
            },
            "messages": [
                {
                    "success": "Data successfully retrieved"
                }
            ]
        }
    ```

### Retrieve a Genres [GET]
Returns a specific Genres.

+ Response 200

    [Genre][]

## List Genres [/genres]
Retrieve a List of all published Genres.

+ Model (application/json)

    ```js
        {
            "data": [
                {
                    "id": 3,
                    "parentId": 0,
                    "title": "Action",
                    "type": "Genre"
                },
                {
                    "id": 4,
                    "parentId": 0,
                    "title": "Spanish",
                    "type": "Genre"
                }
            ],
            "messages": [
                {
                    "success": "Data successfully retrieved"
                }
            ]
        }
    ```

### Retrieve all Genres [GET]
Retrieves all Genres.

+ Response 200

    [List Genres][]

# Group Geoblocking
Represents actions against Geoblocking object

## List Geoblocking [/geoblockings]
Retrieve a List of all published Geoblocking.

+ Model (application/json)

    ```js
        {
            "data": [
                {
                    "id": 1,
                    "title": "Guatemala",
                    "type": "Geoblocking"
                },
                {
                    "id": 2,
                    "title": "Italy",
                    "type": "Geoblocking"
                }
            ],
            "messages": [
                {
                    "success": "Data successfully retrieved"
                }
            ]
        }
    ```

### Retrieve all Geoblocking [GET]
Retrieves all Geoblocking.

+ Response 200

    [List Geoblocking][]

# Group Parental Rating
Represents actions against Parental Rating object

## List Parental Rating [/parental-ratings]
Retrieve a List of all published ParentalRating.

+ Model (application/json)

    ```js
        {
            "data": [
                {
                    "id": 1,
                    "title": "G",
                    "code": "G",
                    "level": 0,
                    "type": "ParentalRating"
                },
                {
                  "id": 2,
                  "title": "PG",
                  "code": "PG",
                  "level": 1,
                  "type": "ParentalRating"
                }
            ],
            "messages": [
                {
                    "success": "Data successfully retrieved"
                }
            ]
        }
    ```

### Retrieve all Parental Rating [GET]
Retrieves all Parental Rating.

+ Response 200

    [List Parental Rating][]

# Group PlayContext
Actions required for playing and tracking video streaming

## Initialize asset streaming [/play/asset/{assetId}/video/{videoId}]
Create the Asset PlayContext required before streaming.

+ Parameters
    + assetId (string, `4962`) ... The id of the Asset.
    + videoId (string, `6538`) ... The id of the VideoAsset.

+ Model (application/json)

    ```js
    {
        "data": {
            "playContext": {
                "locationUri": "http://www.veo.tv/player/user/1811/asset/4962/video/6538/stream/b7648850-1f21-4031-9cb3-e3a19eb800fb",
                "playerState": null,
                "userStream": {
                    "videoId": 6538,
                    "assetId": 4962,
                    "userId": 1181,
                    "streamId": "b7648850-1f21-4031-9cb3-e3a19eb800fb",
                    "expirationDate": null,
                    "interval": -1,
                    "updateDate": 1418330651212,
                    "creationDate": 1418330651212,
                    "state": "CREATED"
                }
            }
        }
    }
    ```

### Create Asset PlayContext [POST]

+ Response 200

    [Initialize asset streaming][]

## Initialize channel streaming [/watch/channel/{channelName}]
Create the Channel PlayContext required before streaming.

+ Parameters
    + channelName (string, `GALA TV HD`) ... The name of the Channel.

+ Model (application/json)

    ```js
    {
        "data": {
            "playContext": {
                "locationUri": "http://www.veo.tv:80/player/user/991580/channel/909/stream/a902f568-04b5-46a6-ae53-9cebde7b54a6",
                "playerState": null,
                "userStream": {
                    "channelNumber": 909,
                    "userId": 991580,
                    "streamId": "a902f568-04b5-46a6-ae53-9cebde7b54a6",
                    "expirationDate": null,
                    "interval": -1,
                    "updateDate": 1420737389235,
                    "creationDate": 1420737389235,
                    "state": "CREATED"
                }
            }
        }
    }
    ```

### Create Channel PlayContext [POST]

+ Response 200

    [Initialize channel streaming][]

## Update Asset PlayContext [/player/user/{userId}/asset/{assetId}/video/{videoId}/stream/{streamId}]
Update the Asset PlayContext while streaming.

+ Parameters
    + userId (string, `1181`) ... The id of the User.
    + assetId (string, `4962`) ... The id of the Asset.
    + videoId (string, `6538`) ... The id of the VideoAsset.
    + streamId (string, `b7648850-1f21-4031-9cb3-e3a19eb800fb`) ... The id of the stream generated with the initial post.

+ Model (application/json)

    ```js
    {
        "data": {
            "playContext": {
                "locationUri": null,
                "playerState": "CONTINUE",
                "userStream": {
                    "videoId": 6538,
                    "assetId": 4962,
                    "userId": 1181,
                    "streamId": "b7648850-1f21-4031-9cb3-e3a19eb800fb",
                    "expirationDate": null,
                    "interval": 60,
                    "updateDate": 1418332300438,
                    "creationDate": 1418331996427,
                    "state": "RETAINED"
                }
            }
        }
    }
    ```

### Update Asset PlayContext [POST]

+ Response 200

    [Update Asset PlayContext][]

## Update Channel PlayContext [/player/user/{accountId}/channel/{channelNumber}/stream/{streamId}]
Update the Channel PlayContext while streaming.

+ Parameters
    + accountId (string, `1181`) ... The accountId of the User.
    + channelNumber (string, `909`) ... The number of the Channel.
    + streamId (string, `a902f568-04b5-46a6-ae53-9cebde7b54a6`) ... The id of the stream generated with the initial post.

+ Model (application/json)

    ```js
    {
        "data": {
            "playContext": {
                "locationUri": null,
                "playerState": "START",
                "userStream": {
                    "channelNumber": 909,
                    "userId": "501000000129-01",
                    "expirationDate": null,
                    "streamId": "a902f568-04b5-46a6-ae53-9cebde7b54a6",
                    "interval": 60,
                    "updateDate": 1420494077906,
                    "creationDate": 1420494077752,
                    "state": "ACQUIRED"
                }
            }
        }
    }
    ```

### Update Channel PlayContext [POST]

+ Response 200

    [Update Channel PlayContext][]

# Group Navigation
Represents actions against SB Navigation objects

## Navigation [/navigation]
Returns all menus for clients (WEB, IOS, Android, ...).

+ Model (application/json)

    ```js
    {
        "data": [
            {
                "id": 1,
                "type": "Navigation",
                "title": "Main menu",
                "key": "main-menu",
                "items": [
                    {
                        "id": 10,
                        "type": "Navigation",
                        "title": "Tele para llevar",
                        "key": "main-menu-tele-para-llevar",
                        "link": "/tv/epg",
                        "icon": null
                    },
                    {
                        "id": 11,
                        "type": "Navigation",
                        "title": "Play",
                        "key": "main-menu-play",
                        "link": "/clubondemand",
                        "icon": null
                    },
                    {
                        "id": 12,
                        "type": "Navigation",
                        "title": "Rentas",
                        "key": "main-menu-rentas",
                        "link": "/tienda",
                        "icon": null
                    }
                ]
            },
            {
                "id": 2,
                "type": "Navigation",
                "title": "Clubondemand",
                "key": "clubondemand",
                "items": [
                    {
                        "id": 20,
                        "type": "Navigation",
                        "title": "Inicio",
                        "key": "clubondemand-inicio",
                        "link": "/clubondemand",
                        "icon": null
                    },
                    {
                        "id": 21,
                        "type": "Navigation",
                        "title": "Películas",
                        "key": "clubondemand-peliculas",
                        "link": "/clubondemand/peliculas",
                        "icon": null
                    },
                    {
                        "id": 22,
                        "type": "Navigation",
                        "title": "Series de TV",
                        "key": "clubondemand-series-de-tv",
                        "link": "/clubondemand/series",
                        "icon": null
                    },
                    {
                        "id": 23,
                        "type": "Navigation",
                        "title": "Telenovelas",
                        "key": "clubondemand-telenovelas",
                        "link": "/clubondemand/telenovelas",
                        "icon": null
                    }
                ]
            },
            {
                "id": 3,
                "type": "Navigation",
                "title": "Tienda",
                "key": "tienda",
                "items": [
                    {
                        "id": 24,
                        "type": "Navigation",
                        "title": "Inicio",
                        "key": "tienda-inicio",
                        "link": "/tienda",
                        "icon": null
                    },
                    {
                        "id": 25,
                        "type": "Navigation",
                        "title": "Catálogo Completo",
                        "key": "tienda-catalogo-completo",
                        "link": "/tienda/peliculas",
                        "icon": null
                    }
                ]
            }
        ]
    }
    ```

### Retrieve all menus [GET]
Retrieves all navigation menus for clients.

+ Response 200

    [Navigation][]

## Navigation item [/navigation/{key}]
Returns a navigation item.

+ Parameters
    + key (string, `main-menu`) ... The key of the navigation.

+ Model (application/json)

    ```js
    {
        "data": {
            "id": 1,
            "type": "Navigation",
            "title": "Main menu",
            "key": "main-menu",
            "items": [
                {
                    "id": 10,
                    "type": "Navigation",
                    "title": "Tele para llevar",
                    "key": "main-menu-tele-para-llevar",
                    "link": "/tv/epg",
                    "icon": null
                },
                {
                    "id": 11,
                    "type": "Navigation",
                    "title": "Play",
                    "key": "main-menu-play",
                    "link": "/clubondemand",
                    "icon": null
                },
                {
                    "id": 12,
                    "type": "Navigation",
                    "title": "Rentas",
                    "key": "main-menu-rentas",
                    "link": "/tienda",
                    "icon": null
                }
            ]
        }
    }
    ```

### Retrieve menu [GET]
Retrieves one navigation menu by key.

+ Response 200

    [Navigation item][]
