FORMAT: 1A

# Veo Core API
More information coming soon...

Please be sure to validate your response examples with [JSONLint][1].

[1]:  http://jsonlint.com/

# Group Business - Distributors
Represents actions against Distributor objects

## Distributor [/distributor/{id}]
Represents a distributor

+ Parameters
    + id (string, `1`) ... The id of the Distributor.

+ Model (application/json)

    ```js
    {
        "data": {
            "id": 1,
            "type": "Distributor",
            "status": "published",
            "name": "televisa.networks.mx",
            "code": "televisa.networks.mx",
            "contact": "Juan Perez"
        },
        "messages": [
            {
                "success": "Data successfully retrieved"
            }
        ]
    }
    ```

### Retrieve a Distributor [GET]
Returns a specific Distributor.

+ Response 200

    [Distributor][]

## List Distributors [/distributor/list]
Returns all Distributors.

+ Model (application/json)

    ```js
    {
        "data": [
            {
                "id": 2,
                "type": "Distributor",
                "status": "published",
                "name": "televisa.networks.mx",
                "code": "televisa.networks.mx",
                "contact": "Juan Perez"
            },
            {
                "id": 2,
                "type": "Distributor",
                "status": "published",
                "name": "televisa.networks.mx",
                "code": "televisa.networks.mx",
                "contact": "Pedro Perez"
            }
        ],
        "messages": [
            {
                "success": "Data successfully retrieved"
            }
        ]
    }
    ```

### Retrieve all Distributors [GET]
Retrieves all distributors.

+ Response 200

    [List Distributors][]


# Group Business - Country
Represents actions against Country object

## Country [/country/{id}]
Represents a country

+ Parameters
    + id (string, `1`) ... The id of the Country.

+ Model (application/json)

    ```js
    {
        "data": {
            "id": 1,
            "parentId": 0,
            "title": "United States",
            "type": "Country",
        },
        "messages": 200
    }
    ```

### Retrieve a Country [GET]
Returns a specific Country.

+ Response 200

    [Country][]

## List Countries [/country/list]
A List of all countries.

+ Model (application/json)

    ```js
    {
    "data": [
        {
            "id": 1,
            "parentId": 0,
            "title": "United States",
            "type": "Country",
        },
        {
            "id": 2,
            "parentId": 0,
            "title": "México",
            "type": "Country",
        }
    ],
    "messages": 200
}
    ```

### Retrieve all Countries [GET]
Retrieves all Countries.

+ Response 200

    [List Countries][]
